# Default values for camel-restapi-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sohaibm/camel-restapi-example
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.1"

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  exposePort: 30111
  targetPort: 8078
  port: 8078

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80