apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-springboot-webservice-producer.fullname" . }}
  labels:
    {{- include "simple-springboot-webservice-producer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "simple-springboot-webservice-producer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-springboot-webservice-producer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
